### PR TITLE
Lock everything by default in giantswarm and kube-system namespaces

### PR DESCRIPTION
**Pull request by jkremser**
issue: https://github.com/giantswarm/roadmap/issues/2815

This pr: installs network-policies-app as a HelmRelease that will effectively lock all the communication to `giantswarm` and `kube-system` namespaces

### Checklist

- [x] Update changelog in CHANGELOG.md.
- [x] Make sure `values.yaml` and `values.schema.json` are valid.
- [x] Update `/examples` if required.

### CODE REVIEW

**Comment by erkanerol** [comment]
I released a new version of cluster-test-suites. Let's see the effect here

/run cluster-test-suites

**Comment by glitchcrab** [comment]
running the tests locally to see if i can figure out what's going on

**Comment by erkanerol** [comment]
@glitchcrab Regarding `prometheus-operator-app` problem in the CI, I created this https://github.com/giantswarm/giantswarm/issues/29287

Regarding the cert-manager issue, I guess it is because of this PR. We are introducing some new limitations in the network and it may break cert-manager jobs. Are you using this version in your local tests?

**Comment by glitchcrab** [comment]
yes, I used this branch to create the WC. I have another CI test currently running and that looks like it will succeed. i think the flakiness of the tests in this PR is related to VCD rather than the actual clusters themselves.

**Comment by erkanerol** [comment]
@glitchcrab VCD is much slower than other providers. I guess we need to make tests more robust.

**Comment by erkanerol** [comment]
Let's retry after increasing timeouts in cluster-test-suites for CAPVCD

/run cluster-test-suites

**Comment by erkanerol** [comment]
@glitchcrab Somehow the last CP node stuck at provisioning state. I observe this in capvcd manager logs

```
2023-12-19T12:11:24.554Z	ERROR	Reconciler error	{"controller": "vcdmachine", "controllerGroup": "infrastructure.cluster.x-k8s.io", "controllerKind": "VCDMachine", "VCDMachine": {"name":"t-a6a3p6sojx39dv3ehv-control-plane-adb0935e-kbd2k","namespace":"org-t-6bneox7er9hhexi8kq"}, "namespace": "org-t-6bneox7er9hhexi8kq", "name": "t-a6a3p6sojx39dv3ehv-control-plane-adb0935e-kbd2k", "reconcileID": "e5649070-3288-4dc8-9fdf-41fdfed652b1", "error": "Error while deploying infra for the machine [t-a6a3p6sojx39dv3ehv/t-a6a3p6sojx39dv3ehv-h5xc8]; error waiting for VM power-on task completion: task did not complete successfully:  [500:INTERNAL_SERVER_ERROR] - [ 3eaba7e4-8930-40c1-ba05-b0c4fd54dd70 ] Unable to perform this action. Contact your cloud administrator.", "errorVerbose": "task did not complete successfully:  [500:INTERNAL_SERVER_ERROR] - [ 3eaba7e4-8930-40c1-ba05-b0c4fd54dd70 ] Unable to perform this action. Contact your cloud administrator.\nError while deploying infra for the machine [t-a6a3p6sojx39dv3ehv/t-a6a3p6sojx39dv3ehv-h5xc8]; error waiting for VM power-on task completion\ngithub.com/vmware/cluster-api-provider-cloud-director/controllers.(*VCDMachineReconciler).reconcileNormal\n\t/home/circleci/project/controllers/vcdmachine_controller.go:867\ngithub.com/vmware/cluster-api-provider-cloud-director/controllers.(*VCDMachineReconciler).Reconcile\n\t/home/circleci/project/controllers/vcdmachine_controller.go:189\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/circleci/project/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/circleci/project/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/circleci/project/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/circleci/project/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:235\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598"}
```

Can we ask neoedge what the problem is?

**Comment by vxav** [comment]
It might have been resource contention if other tests were running perhaps.
I also see a vAPP `t-oviv4ebjzwtnpwzcvw` that seems stuck.

**Comment by erkanerol** [comment]
@vxav There were only 1 running tests with 2 clusters.

**Comment by vxav** [comment]
Let's see how far that one goes

**Comment by erkanerol** [comment]
We need this fix for CAPVCD too https://github.com/giantswarm/cluster-vsphere/pull/135 but feel free to merge this now :D

**Pull request merged**
