### PR TITLE
Re-organize values schema

### PR DESCRIPTION
**Pull request by marians**
Towards https://github.com/giantswarm/roadmap/issues/2132

In this branch/PR we collect a number of breaking schema changes, to be released in concert.

### Checklist

- [x] Update changelog in CHANGELOG.md.
- [x] Make sure `values.yaml` and `values.schema.json` are valid.
- [x] Update `/examples` if required.

### CODE REVIEW

**Review by erkanerol — APPROVED** [review]
LGTM.

helm templating seems OK but it is really hard to catch issues by reviewing. I couldn't catch anything. 

@marians Did you test this structure somewhere?

**Comment by vxav** [comment]
Wait, I tested to upgrade my values with the yq script (nice one btw!) and the schema rejects empty `connectivity.proxy.secretName`
We need to allow it because cluster-app-operator takes care of setting it based on the MC's.

Also I got a `providerSpecific.userContext.secretRef: Additional property useSecretRef is not allowed`
I have `useSecretRef: true`

**Comment by erkanerol** [comment]
I deployed a cluster with 0.11.2. Applied values.yaml changes with `yq`  as explained in this PR. Then upgraded to this version. Results:
- It failed on the first try because of empty `connectivity.proxy.secretName`.  After removing that parameter, it worked.

- The diff as below between helm revisions after cleaning version diffs.
```
➜ diff revision1.yaml revision2.yaml
439c439
<           enable-admission-plugins: NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota,PersistentVolumeClaimResize,DefaultStorageClass,Priority,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
---
>           enable-admission-plugins: "DefaultStorageClass,DefaultTolerationSeconds,LimitRanger,MutatingAdmissionWebhook,NamespaceLifecycle,PersistentVolumeClaimResize,Priority,ResourceQuota,ServiceAccount,ValidatingAdmissionWebhook"
848,851d847
<   rdeId:
<   parentUid:
<   useAsManagementCluster: false
<   skipRDE:

```

  The first is just order change. The second is because we only set this variable if they exist in this PR. It is how it should be.

- Regarding proxy secret name discussion above, the interface between cluster-apps-operator and cluster-<provider> apps is only the name of the secret. We use that secret as default in this chart https://github.com/giantswarm/cluster-cloud-director/blob/main/helm/cluster-cloud-director/templates/_helpers.tpl#L67 and that part is not changed in this PR. Users who set `.Values.proxy.secretName` to customize the secret will be OK if they apply provided `yq` command.

Shortly, I think we can merge this PR.

**Review by vxav — APPROVED** [review]

**Pull request merged**
