### PR TITLE
Add support for Flatcar

### PR DESCRIPTION
**Pull request by vxav**
Adds support for Flatcar and maintains support for Ubuntu:

**For Flatcar**

- Set `providerSpecific.vmBootstrapFormat: ignition`
- Set `kubernetesVersion: v1.xx.yy` (without `+vmware.1`)
- Set `controlPlane.image.repository: giantswarm`

**For Ubuntu (default)**

- Set `providerSpecific.vmBootstrapFormat: cloud-config`
- Set `kubernetesVersion: v1.xx.yy+vmware.1`
- Set `controlPlane.image.repository: projects.registry.vmware.com/tkg`

Requires a supported build of the CAPVCD controller for Flatcar: https://github.com/giantswarm/cluster-api-provider-cloud-director/pull/14

**Tested**:

- ✅ Cluster creation (Ubuntu - default values)
- ✅ Cluster creation (Flatcar)
- ✅ Static routes, NTP, NIC IPs
- ✅ 1-CP WC Ubuntu to Flatcar
- ✅ 3-CP WC Ubuntu to Flatcar

### CODE REVIEW

**Comment by vxav** [comment]
Works with ubuntu ☝️

**Comment by vxav** [comment]
This fixed the ignition templating issue ☝️

**Comment by vxav** [comment]
☝️  Used with https://github.com/giantswarm/cluster-api-provider-cloud-director/pull/14/commits/8b3dfce690de22d9d9badfa1da3b301aaa3d77e5

Works with workaround: After 1st control plane VM is created, change NIC to DHCP and change LB Pool to the new DHCP IP.
VM doesn't get an IP with static IP pool mode <= Next focus.

**Comment by vxav** [comment]
Works but if DNS2 is empty it will cause an empty DNS config ☝️

**Comment by vxav** [comment]
☝️  It works with 👇 
https://github.com/giantswarm/cluster-api-provider-cloud-director/pull/14/commits/ada6d8f80b25af9c66ee3db2c9a677a76b969e61

**Comment by vxav** [comment]
SSH fixed with ☝️

**Comment by vxav** [comment]
Statis routes work with this ☝️

**Comment by vxav** [comment]
Works ☝️ 🎉 
With 👇 
https://github.com/giantswarm/cluster-api-provider-cloud-director/pull/14/commits/0312b6cb7beef0413f1142f241b1b18ab3150610

**Comment by vxav** [comment]
@giantswarm/team-rocket I think this is ready to merge.
Tested against MC running non-modified CAPVCD controller so no breaking change.

**Review by erkanerol — APPROVED** [review]

**Pull request merged**
