### PR TITLE
move static route to unit

### PR DESCRIPTION
**Pull request by vxav**
If a node reboots, the routes aren't installed as it happens in kubeadm.

It should be a unit in ignition. Context: https://gigantic.slack.com/archives/C02EVLE9W/p1714374192860579

I had a race condition issue when using a dedicated networkd unit so I moved the ip route add commands to the script that sets up networking.

(Rework of https://github.com/giantswarm/cluster-cloud-director/pull/293)

### CODE REVIEW

**Review by glitchcrab — APPROVED** [review]

**Comment by vxav** [comment]
I kinda want the green check though
/run cluster-test-suites

**Comment by glitchcrab** [comment]
this PR seems to repeatably fail on the upgrade test:

```
  {"level":"info","ts":"2024-05-14T16:26:56Z","msg":"Found KubeadmControlPlane condition MachinesSpecUpToDate with Status='False' and Reason='RollingUpdateInProgress', expected condition with Status='True' and Reason=''"}
  [FAILED] in [It] - /app/internal/upgrade/upgrade.go:146 @ 05/14/24 16:27:17.439
• [FAILED] [1200.070 seconds]
Basic upgrade test upgrade [It] successfully finishes control plane nodes rolling update if it is needed
/app/internal/upgrade/upgrade.go:106

  [FAILED] Timed out after 1200.001s.
  Expected
      <bool>: false
  to be true
  In [It] at: /app/internal/upgrade/upgrade.go:146 @ 05/14/24 16:27:17.439
```

**Comment by vxav** [comment]
In the past I've [encountered](https://gigantic.slack.com/archives/C04KA9DBMB2/p1714404080396909?thread_ts=1714395613.434989&cid=C04KA9DBMB2) a CP nodes isn't draining because of `cert-manager`, I bet it'll be that. I'll try again manually with 3 CP nodes (worked with 1)

**Comment by vxav** [comment]
I tested manually
- Create WC on 0.51.0
- Upgrade to this PR
worked fine

**Comment by vxav** [comment]
Last one and then I'll give up on E2E passing for this PR
/run cluster-test-suites

**Comment by vxav** [comment]
I was babysitting this run. It was working but slow and timed out during the rolling of the CP nodes.

**Pull request merged**
