### PR TITLE
Enable teleport by default

### PR DESCRIPTION
**Pull request by tuladhar**
Towards https://github.com/giantswarm/roadmap/issues/3101

This PR:

- Enables teleport by default

### Testing

Description on how cluster-cloud-director can be tested.

- [ ] fresh install works
- [ ] upgrade from previous version works

#### Other testing

Description of features to additionally test for cluster-cloud-director installations.

- [ ] check reconciliation of existing resources after upgrading
- [ ] X still works after upgrade
- [ ] Y is installed correctly

### Checklist

- [ ] Update changelog in CHANGELOG.md.
- [ ] Make sure `values.yaml` and `values.schema.json` are valid.
- [ ] Update `/examples` if required.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by tuladhar** [comment]
E2E failed with:
```
• [FAILED] [1500.293 seconds]
Common tests observability-bundle apps [It] all observability-bundle apps are deployed without issues
/app/internal/common/apps.go:46

  [FAILED] Timed out after 1500.003s.
  Expected
      <bool>: false
  to be true
  In [It] at: /app/internal/common/apps.go:69 @ 04/17/24 10:04:43.903
```

**Comment by tuladhar** [comment]
[E2E failed with:](https://tekton.ci.giantswarm.io/#/namespaces/tekton-pipelines/pipelineruns/pr-cluster-cloud-director-287-cluster-test-suiteswxrn7?pipelineTask=run-tests&taskRunName=pr-cluster-cloud-di28cb153ef3d749d58774d6d1c6c82dc0-run-tests-1&step=run-tests)
```
• [FAILED] [120.001 seconds]
Basic upgrade test cert-manager ClusterIssuers [It] cert-manager default ClusterIssuers are present and ready
/app/internal/common/certmanager.go:34

  [FAILED] Timed out after 120.001s.
  Expected success, but got an error:
      <*errors.StatusError | 0xc00079a3c0>: 
      [clusterissuers.cert-manager.io](http://clusterissuers.cert-manager.io/) "selfsigned-giantswarm" not found
      {
          ErrStatus: {
              TypeMeta: {Kind: "Status", APIVersion: "v1"},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "[clusterissuers.cert-manager.io](http://clusterissuers.cert-manager.io/) \"selfsigned-giantswarm\" not found",
              Reason: "NotFound",
              Details: {
                  Name: "selfsigned-giantswarm",
                  Group: "[cert-manager.io](http://cert-manager.io/)",
                  Kind: "clusterissuers",
                  UID: "",
                  Causes: nil,
                  RetryAfterSeconds: 0,
              },
              Code: 404,
          },
      }
  In [It] at: /app/internal/common/certmanager.go:39 @ 04/17/24 11:47:23.034
------------------------------
```

**Review by vxav — APPROVED** [review]

**Pull request merged**
