### PR TITLE
Use cluster chart to render Cluster resource

### PR DESCRIPTION
**Pull request by glitchcrab**
towards https://github.com/giantswarm/giantswarm/issues/31697

This PR:

- adds/changes/removes etc

### Testing

Description on how cluster-cloud-director can be tested.

- [ ] fresh install works
- [ ] upgrade from previous version works

#### Other testing

Description of features to additionally test for cluster-cloud-director installations.

- [ ] check reconciliation of existing resources after upgrading
- [ ] X still works after upgrade
- [ ] Y is installed correctly

### Checklist

- [x] Update changelog in CHANGELOG.md.
- [x] Make sure `values.yaml` and `values.schema.json` are valid.
- [ ] Update `/examples` if required.

### CODE REVIEW

**Comment by anvddriesch** [comment]
Nice!
Seeing that it's still WIP I'm not reviewing anything just yet but coupling node classes and cluster chart change makes sense to me.
(Or were you thinking to release them separate and rebase?)

**Comment by vxav** [comment]
The story is there 🙂 
https://github.com/giantswarm/giantswarm/issues/31112

Thanks, I'll release it then

**Comment by glitchcrab** [comment]
> Nice! Seeing that it's still WIP I'm not reviewing anything just yet but coupling node classes and cluster chart change makes sense to me. (Or were you thinking to release them separate and rebase?)

my aim was to rebase once your nodeclasses PR is merged - i just wanted to get started with this issue :)

**Comment by glitchcrab** [comment]
closing in favour of a new PR

**Pull request closed without merging**
