### PR TITLE
Set template and K8s default values

### PR DESCRIPTION
**Pull request by vxav**
This PR:

- Adds defaults for VM templates and Kubernetes version to v1.25.13

### Testing

Description on how {APP-NAME} can be tested.

- [ ] fresh install works
- [ ] upgrade from previous version works

#### Other testing

Description of features to additionally test for {APP-NAME} installations.

- [ ] check reconciliation of existing resources after upgrading
- [ ] X still works after upgrade
- [ ] Y is installed correctly

### Checklist

- [ ] Update changelog in CHANGELOG.md.
- [ ] Make sure `values.yaml` and `values.schema.json` are valid.
- [ ] Update `/examples` if required.

### CODE REVIEW

**Review by glitchcrab — APPROVED** [review]
makes sense to me

**Review by ssyno — APPROVED** [review]

**Comment by vxav** [comment]
Hmm, good point, it seems the `patternProperties` sections doesn't respect the defaults set at the top of the schema. I'm going to do some more YAMLing

**Comment by erkanerol** [comment]
Can't we set the default node class in values.yaml as we do in other providers?

**Comment by vxav** [comment]
I was trying to set the default template value in one place only.
Also `helm-values-gen`/linter probably won't like us setting things manually in the values as it generates them from the schema.

**Comment by vxav** [comment]
Oh hang on, that's interesting https://github.com/giantswarm/cluster-azure/blob/main/helm/cluster-azure/values.schema.json#L828

**Comment by vxav** [comment]
Well that was a rabbit hole... On pause until [this](https://gigantic.slack.com/archives/C01BYMF6RN0/p1711448781843269) is figured out

**Comment by vxav** [comment]
Closing as I will include this in https://github.com/giantswarm/cluster-cloud-director/pull/283

**Pull request closed without merging**
