### PR TITLE
Fix `.connectivity.proxy.secretName` defaulting

### PR DESCRIPTION
**Pull request by kopiczko**
Found it while trying to re-create `glasgow`.

### CODE REVIEW

**Review by erkanerol — APPROVED** [review]

**Comment by erkanerol** [comment]
@kopiczko just delete the parameter from values.yaml if it is an empty string.

**Comment by kopiczko** [comment]
> @kopiczko just delete the parameter from values.yaml if it is an empty string.

But I still would have to update the schema, no?

**Comment by kopiczko** [comment]
I tested it with `glasgow` and it works. Going with it. I prefer to have empty value defined in `values.yaml`. If that's not desired then it can be corrected in a future PR.

**Pull request merged**
