### PR TITLE
Move `.kubernetesVersion` to `.internal.kubernetesVersion`

### PR DESCRIPTION
**Pull request by marians**
Towards https://github.com/giantswarm/roadmap/issues/2132

- Move `.kubernetesVersion` to `.internal.kubernetesVersion` (like in Azure and AWS)

### Checklist

- [x] Update changelog in CHANGELOG.md.
- [x] Make sure `values.yaml` and `values.schema.json` are valid.
- [x] Update `/examples` if required.

### CODE REVIEW

**Comment by marians** [comment]
@vxav In AWS and Azure, the default value of this field is defined to be the actual kubernetes version default value. Which value would that be in the case of VCD? In the examples I see `v1.22.9+vmware.1` in use.

**Comment by vxav** [comment]
Yes, for now the appended `+vmware.1` is required because the controller will do a string replacement to pull the right images from their repos. This is bound to disappear in the future but for now we have to keep it.

**Comment by marians** [comment]
@vxav Currently the default for `kubernetesVersion` in the schema is empty. I would set it to `v1.22.9+vmware.1` then. OK?

**Comment by vxav** [comment]
If possible I'd like to leave it empty for now.

Context here 👉  https://github.com/giantswarm/roadmap/issues/2514

**Comment by marians** [comment]
Default is empty, I just removed `"default: ""` from the schema, as this is not needed then.

**Review by vxav — APPROVED** [review]

**Pull request merged**
