### PR TITLE
remove default-policies and enable DNS policies

### PR DESCRIPTION
**Pull request by mcharriere**
Signed-off-by: Matias Charriere <matias@giantswarm.io>

This PR:

- Remove default policies from cilium-app
- Install DNS policies from network-policies-app

Towards https://github.com/giantswarm/roadmap/issues/3261

### Testing

Description on how cluster-cloud-director can be tested.

- [ ] fresh install works
- [ ] upgrade from previous version works

#### Other testing

Description of features to additionally test for cluster-cloud-director installations.

- [ ] check reconciliation of existing resources after upgrading
- [ ] X still works after upgrade
- [ ] Y is installed correctly

### Checklist

- [ ] Update changelog in CHANGELOG.md.
- [ ] Make sure `values.yaml` and `values.schema.json` are valid.
- [ ] Update `/examples` if required.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by mcharriere** [comment]
there we go :)

**Review by erkanerol — APPROVED** [review]

**Pull request merged**
