### PR TITLE
Remove etcd and dns images from kubeadmcontrolplane

### PR DESCRIPTION
**Pull request by vxav**
This pr removes our ability to set etcd images (and coredns which wasn't used like that anyways). This means it will be handled automatically by kubeadm.

This also aligns with our cloud providers.

https://gigantic.slack.com/archives/CLPMFRVU6/p1712831360621509?thread_ts=1712831054.292869&cid=CLPMFRVU6

### Testing

Description on how cluster-cloud-director can be tested.

- [ ] fresh install works
- [ ] upgrade from previous version works

#### Other testing

Description of features to additionally test for cluster-cloud-director installations.

- [ ] check reconciliation of existing resources after upgrading
- [ ] X still works after upgrade
- [ ] Y is installed correctly

### Checklist

- [ ] Update changelog in CHANGELOG.md.
- [ ] Make sure `values.yaml` and `values.schema.json` are valid.
- [ ] Update `/examples` if required.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by erkanerol** [comment]
Is it expected to have some failures in CI? There are some diff in doc jobs.

**Comment by vxav** [comment]
Yeah it's a bug when `additionalProperties` is set.
See https://github.com/giantswarm/cluster-cloud-director/pull/297#issuecomment-2098616809

**Review by erkanerol — APPROVED** [review]

**Pull request merged**
