### PR TITLE
Add items schema for `.network.staticRoutes`

### PR DESCRIPTION
**Pull request by marians**
This PR:

- adds items schema for `.network.staticRoutes`

This is required for proper validation and generating a data entry form for this app (towards https://github.com/giantswarm/roadmap/issues/1181)

### Checklist

- [x] Update changelog in CHANGELOG.md.
- [x] Make sure `values.yaml` and `values.schema.json` are valid.
- [ ] Update Lastpass values if required.

### CODE REVIEW

**Comment by marians** [comment]
It appears as if this change is not being validated in CI.

`values.yaml not included in this PR`

https://github.com/giantswarm/cluster-cloud-director/actions/runs/3593276801/jobs/6050029331

**Comment by vxav** [comment]
CI looks ok to me. Usually it complains when one is changed and not the other (values and schema) but you can ignore

**Comment by jkremser** [comment]
@marians btw. I made an improvement to the devctl recently on this schema gh action - https://github.com/giantswarm/devctl/pull/464 but all the repos are still doing the naive way of just checking if both files were changed, no real validation

**Review by jkremser — APPROVED** [review]

**Comment by marians** [comment]
Waiting for https://github.com/giantswarm/cluster-cloud-director/pull/62

**Comment by marians** [comment]
Got a schema validation error which is not related to the changes in this PR:

```
helm/cluster-cloud-director/values.yaml: fail: nodePools: Invalid type. Expected: object, given: array
```

I suggest to handle that separately.

**Pull request merged**
