### PR TITLE
Remove nodeclasses

### PR DESCRIPTION
**Pull request by glitchcrab**
https://github.com/giantswarm/giantswarm/issues/31193

This PR:

- adds/changes/removes etc

### Testing

Description on how cluster-cloud-director can be tested.

- [ ] fresh install works
- [ ] upgrade from previous version works

#### Other testing

Description of features to additionally test for cluster-cloud-director installations.

- [ ] check reconciliation of existing resources after upgrading
- [ ] X still works after upgrade
- [ ] Y is installed correctly

### Checklist

- [ ] Update changelog in CHANGELOG.md.
- [ ] Make sure `values.yaml` and `values.schema.json` are valid.
- [ ] Update `/examples` if required.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by glitchcrab** [comment]
@anvddriesch unfortunately we can't use the E2E tests on PRs which introduce breaking changes to the values schema - the tests can only run with values provided by the test suite. 

We have to test this manually (fresh WC and also upgrade a WC from the last release), then once this PR is merged+released we need to update the values used by `standup`. Finally we need to release `cluster-test-suites` to use the new values 😐

**Comment by glitchcrab** [comment]
Although apparently E2E tests worked for a fresh cluster when I removed classes from vsphere 😕 

https://github.com/giantswarm/cluster-vsphere/pull/232#issuecomment-2217317583

**Comment by vxav** [comment]
Did you not set `additionalProperties` to `true` in vSphere? Which would explain why it worked then (not an actual test in hindsight) and fails here 
```
ReleaseStatus='values-schema-violation', ReleaseReason='values don't meet the specifications of the schema(s) in the following chart(s):\ncluster-cloud-director:\n- global.nodePools.worker: Additional property class is not allowed\n- global.nodePools.worker: Additional property class is not allowed\n- global.providerSpecific: Additional property nodeClasses is not allowed
```

**Comment by anvddriesch** [comment]
image
manual testing with the correct values from herehttps://github.com/giantswarm/cluster-standup-teardown/pull/122 succeeded

**Review by anvddriesch — APPROVED** [review]

**Pull request merged**
