### PR TITLE
Update machine template: `flatcar-stable-3815.2.1-kube-v1.25.16`

### PR DESCRIPTION
**Pull request by tuladhar**
Towards https://github.com/giantswarm/giantswarm/issues/30385

This PR:

- Updates machine template to newer Flatcar version with includes teleport v15.1.7 binary. 

**WARNING: This will roll CP and worker nodes.**

### Testing

Description on how cluster-cloud-director can be tested.

- [ ] fresh install works
- [ ] upgrade from previous version works

#### Other testing

Description of features to additionally test for cluster-cloud-director installations.

- [ ] check reconciliation of existing resources after upgrading
- [ ] X still works after upgrade
- [ ] Y is installed correctly

### Checklist

- [ ] Update changelog in CHANGELOG.md.
- [ ] Make sure `values.yaml` and `values.schema.json` are valid.
- [ ] Update `/examples` if required.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Review by vxav — APPROVED** [review]

**Review by vxav — CHANGES_REQUESTED** [review]
Hold fire, I'm seeing some issues with kubeadm starting with this PR

**Comment by vxav** [comment]
image

**Review by erkanerol — APPROVED** [review]

**Comment by vxav** [comment]
FYI @erkanerol, the e2e wasn't meaningful here because the default values were overriden by the test suite values. I released it with https://github.com/giantswarm/cluster-test-suites/pull/263, now it will use the cluster chart defaults.

**Review by vxav — APPROVED** [review]

**Comment by vxav** [comment]
That's fine, it's just cert-manager failing on one suite (been a while), feel free to merge @tuladhar

**Pull request merged**
