### PR TITLE
Add service priority property and label

### PR DESCRIPTION
**Pull request by marians**
Towards https://github.com/giantswarm/giantswarm/issues/13342

This PR adds the capability to configure the cluster's service priority as defined in [this RFC](https://github.com/giantswarm/rfc/tree/main/classify-cluster-priority).

The implementation is copied from cluster-azure.

### CODE REVIEW

**Comment by marians** [comment]
This has to wait for https://github.com/giantswarm/cluster-cloud-director/pull/152 in order to update the generated values.yaml

**Comment by vxav** [comment]
We should remove the existing field then https://github.com/giantswarm/cluster-cloud-director/pull/154/files#diff-6e53353f188ce9fada1c96ca868b379c066de1c6e295d6d0b115a55d8539ebb6L80

**Comment by marians** [comment]
> We should remove the existing field then https://github.com/giantswarm/cluster-cloud-director/pull/154/files#diff-6e53353f188ce9fada1c96ca868b379c066de1c6e295d6d0b115a55d8539ebb6L80

Good catch! I haven't seen that one. This makes this a breaking change, technically. We might want to keep this open and plan when to do breaking changes.

**Comment by vxav** [comment]
Technically yes but we pretty much never set this field and use default values so far so I suppose it's fine.
However, maybe it would make sense to work all the schema change PRs to a branch to do them all at once?

**Comment by marians** [comment]
Closing this one. I'll move a bunch of properties in grouped PRs.

**Pull request closed without merging**
