### PR TITLE
Support local registry caches

### PR DESCRIPTION
**Pull request by uvegla**
Towards: https://github.com/giantswarm/roadmap/issues/3460

Related to: https://github.com/giantswarm/cluster/pull/178

### Testing

Description on how cluster-cloud-director can be tested.

- [ ] fresh install works
- [ ] upgrade from previous version works

#### Other testing

Description of features to additionally test for cluster-cloud-director installations.

- [ ] check reconciliation of existing resources after upgrading
- [ ] X still works after upgrade
- [ ] Y is installed correctly

### Checklist

- [x] Update changelog in CHANGELOG.md.
- [ ] Make sure `values.yaml` and `values.schema.json` are valid.
- [ ] Update `/examples` if required.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by glitchcrab** [comment]
checked the failing test - it's because the observability bundle failed to upgrade correctly. it deployed just fine in the standard test though so let's ignore that failure.

**Comment by erkanerol** [comment]
> checked the failing test - it's because the observability bundle failed to upgrade correctly. it deployed just fine in the standard test though so let's ignore that failure.

Do we know why the observability bundle failed? I observed the same issue in CAPV. Did you check the details?

**Pull request merged**
